### ISSUE TITLE
Can't make additional rows/columns via keyboard

### ISSUE THREAD

**Issue by scraperdragon** [theodi/comma-chameleon#68]
What I tried (from a blank sheet.)
Type into column A, press tab, moves to B
Type into column B, press tab, moves to C
Type into column C, press tab, nothing happens.
Press Enter. nothing happened.

What I expected:
A column 'D' to be created; A row '2' to be created. 
<s>Could not find menu items which allowed for creation of new columns.</s>

**Comment by scraperdragon** [comment]
Ah, you need to right click. Wasn't obvious to me... might still be worth considering.

**Comment by scraperdragon** [comment]
Reopened: not being able to add new records with Enter is actually a bit of a bigger problem.

**Comment by pezholio** [comment]
Cool, thanks. I think those are some good ideas. Also probably worth having the option to add new rows / columns via the main menu too.

**Comment by jennybc** [comment]
I think I have the same question:

If I'm creating a csv *de novo* how am I supposed to add a row?

**Comment by Stephen-Gates** [comment]
Agreed. It took me a while to discover that insert/remove row/column features are only available by right clicking in the table. +1 for both keyboard shortcuts and entries in the Edit menu. Should be able to select a row/column and press delete to remover the row/column.

**Comment by chris48s** [comment]
HandOnTable natively supports a variety of keyboard shortcuts: https://github.com/handsontable/handsontable/wiki/Keyboard-Shortcuts (all of which are supported apart from 'merge cells')

I agree that it would be useful to have some additional keyboard shortcuts/navigation, but I'd propose that `Enter` is not the right choice for 'insert row below' given that this already toggles between select and edit mode. Although it is possible to intercept keystrokes using the `beforeKeyDown` event: http://docs.handsontable.com/0.16.1/tutorial-callbacks.html I'm in favour of keeping the default HandsOnTable keyboard shortcuts and defining additional shortcuts using electron's `accelerators`.
I've submitted a PR which proposes several improvements addressing the issues raised in this thread at PR #128. As a 'first draft' approach, I've added shortcuts for:
`Alt+W`: Insert row above
`Alt+S`: Insert row below
`Alt+A`: Insert row left
`Alt+D`: Insert row right
as using the WSAD keys for Up/Down/Left/Right is a reasonably well known convention (at least within gaming, maybe not so much elsewhere?) and not assigned any shortcuts to Remove Row and Remove Column. I'm not particularly committed to those choices - especially if others have better ideas.

Keyboard shortcuts are one of those things where you really want to get them right first time. You don't want to get your userbase used to one set of shortcuts and then pull the rug out from under them (although there is probably a bit more leeway while you're still releasing 0.x versions). Some feedback/discussion on this would be useful. For context, there are quite a lot of key-combinations that are taken by other keyboard shortcuts already defined:

`CmdOrCtrl+H`: Hide Comma Chameleon
`CmdOrCtrl+Shift+H`: Hide Others
`CmdOrCtrl+Q`: Quit

`CmdOrCtrl+N`: New
`CmdOrCtrl+O`: Open Csv
`CmdOrCtrl+I`: Import Excel file
`CmdOrCtrl+S`: Save
`Shift+CmdOrCtrl+S`: Save As.. Csv
`CmdOrCtrl+D`: Export as Datapackage
`CmdOrCtrl+G`: Export to Github
`CmdOrCtrl+Shift+G`: Add file to Github

`CmdOrCtrl+Z`: Undo
`Shift+CmdOrCtrl+Z`: Redo
`CmdOrCtrl+X`: Cut
`CmdOrCtrl+C`: Copy
`CmdOrCtrl+V`: Paste
`CmdOrCtrl+A`: Select All

`Alt+CmdOrCtrl+I`: Toggle DevTools
`Shift+CmdOrCtrl+V`: Validate

`CmdOrCtrl+M`: Minimize
`CmdOrCtrl+W`: Close

..and some combinations may already be globally in use by the various operating systems (Linux, Windows, Mac) that the app supports and hence inappropriate choices.

**Comment by pezholio** [comment]
@scraperdragon @jennybc @Stephen-Gates How do these proposed shortcuts sound to you? As @chris48s says, we should probably get these right (or as right as possible) before implementing and releasing, so any thoughts would be welcome!

**Comment by pezholio** [comment]
For me, I think these shortcuts sound sensible. I can't see any other examples of keyboard shortcuts for inserting rows in any other spreadsheet application (that I can get access to anyway), so this could be a useful addition. 

A possible alternative to the w,a,s,d layout could be i,j,k,l, which is used in vim, but I'm not sure if this would be in any way 'better'. As a right handed person though, this certainly *feels* like it might be quicker to reach for when using the keyboard exclusively, and also is a standard adopted outside the world of gaming.

**Comment by pezholio** [comment]
My mistake, vim uses h,j,k,l

**Comment by Stephen-Gates** [comment]
I like the point about right-handed person but no strong preference.

**Comment by jennybc** [comment]
> I can't see any other examples of keyboard shortcuts for inserting rows in any other spreadsheet application

I have the most experience with Excel and Google Sheets, but such a shortcut is not necessary in these applications, because the Sheet is generally much larger than current data. You don't need to add rows and columns very often; you just need to move the cursor into existing cells in adjacent rows or columns.

I haven't used CommaChameleon in a while but as I recall, the sheet is growing as you enter data? So the need to add columns and, especially, rows is huge. I think the reason people hope that return or enter or tab will add a row or column is because that's what they've come to expect from Excel / Google Sheets.

The proposed shortcuts seems a bit cumbersome to me, when you are conditioned to get the same end result with a simple return/enter or tab.

**Comment by Stephen-Gates** [comment]
I agree that `Tab` and `Enter` seem natural choices but we also need keyboard shortcuts.

## Adding Columns
In Excel, Sheets, and Comma Chameleon, `Tab` moves you to the next cell on the right.
In Sheets and Comma Chameleon, if you're in the last column and press `Tab`, nothing happens.

You could change Comma Chameleon so that if you press `Tab` and you're in the last column, you add a column to the right.

You still need a keyboard shortcut to insert a column in-between existing columns.

## Adding Rows
In Excel and Sheets pressing `Enter` moves you down a row. 
In Sheets and Comma Chameleon, if you're in the last row and press `Enter`, nothing happens.

In Excel and Sheets pressing `Enter` when you're not in the last row, moves the cursor to the next row. The cursor is placed to mimic the entries you made in the previous rows. E.g. if you entered one value, pressing `Enter` moves the cursor directly below. If you entered 2 values in the row, then pressing `Enter`, the cursor drops and goes under your first entry. This doesn't appear to be totally consistent.

I guess Excel and Sheets are trying to mimic how your entering data.

So in Comma Chameleon,  if you're in the last row when you press `Enter`, add a new row to the bottom and move the cursor to one of:

- column A 
- the below the current column
- use some smarts to determine which column

You still need a keyboard shortcut to insert a row above/below existing columns.

**Comment by pezholio** [comment]
Yeah, I like this solution. As @jennybc says, it's a little cumbersome to have to use a key combination to insert rows and columns as you're editing a csv. Using tab and enter feels much more natural. We could keep the `Alt+*` combinations for inserting rows above and below and left and right, and then use tab and enter to expand the CSV as the user goes. How does that sound?

**Comment by Stephen-Gates** [comment]
Sounds good to me

**Comment by jennybc** [comment]
I agree this all sounds good. I do really think tab and enter should add a row or column when you've reached the lower right corner of the existing sheet. For the "data entry" workflow. But I would be happy to use a more involved shortcut to **insert** a row or column.

**Comment by pezholio** [comment]
Fixed by #128 and #129

**Comment by Stephen-Gates** [comment]
Works a treat- thank you 🎄🎅🏻

**Comment by cboettig** [comment]
The use of `Enter` to create a new row works swell.  However, the use of `tab` does not create a new column for me, though when not on the right edge it does move me to to the cell to the right (as expected).  More pointedly, the hotkey commands shown in the menu (on Mac, Apple-I to "insert row above" fail with a Javascript error:


```
Uncaught Exception:
ReferenceError: mainWindow is not defined
    at exports.menu.submenu.click (/private/var/folders/y8/0wn724zs10jd79_srhxvy49r0000gn/T/AppTranslocation/33040234-83C4-4090-BD96-70AA399FE56D/d/Comma Chameleon.app/Contents/Resources/app/main/menu.js:204:11)
    at MenuItem.click (/private/var/folders/y8/0wn724zs10jd79_srhxvy49r0000gn/T/AppTranslocation/33040234-83C4-4090-BD96-70AA399FE56D/d/Comma Chameleon.app/Contents/Resources/electron.asar/browser/api/menu-item.js:81:16)
    at Function.delegate.executeCommand (/private/var/folders/y8/0wn724zs10jd79_srhxvy49r0000gn/T/AppTranslocation/33040234-83C4-4090-BD96-70AA399FE56D/d/Comma Chameleon.app/Contents/Resources/electron.asar/browser/api/menu.js:119:40)
```

Inserting rows with the right-click menu works fine, though the dialog box doesn't show the (failing) short-cut keys for these commands.  (and a right-click menu may not be intuitive to some users).  


Apologies if I should be opening this in a new thread.  Overall very impressive project here, I particularly like what you've done with the lightweight schema integration :smile:
